name: AMR-Wind Formatting

on:
  push:
    branches: [development]
    paths:
      - 'amr-wind/**'
      - 'unit_tests/**'
      - '.github/workflows/format.yml'
  pull_request:
    branches: [development]
    paths:
      - 'amr-wind/**'
      - 'unit_tests/**'
      - '.github/workflows/format.yml'

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: './amr-wind ./unit_tests'
        exclude: '.'
        extensions: 'H,h,cpp'
        clangFormatVersion: 11
